version: "3.8"

services:
  # --------------------
  # ZOOKEEPER
  # --------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - net

  # --------------------
  # KAFKA BROKER 1
  # --------------------
  kafka1:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks: [net]

  # --------------------
  # KAFKA BROKER 2
  # --------------------
  kafka2:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka2
    depends_on: [zookeeper]
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks: [net]

  # --------------------
  # KAFKA BROKER 3
  # --------------------
  kafka3:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka3
    depends_on: [zookeeper]
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks: [net]

  # --------------------
  # MONGO (Graylog)
  # --------------------
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks: [net]

  # --------------------
  # OPENSEARCH (Graylog Index)
  # --------------------
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks: [net]

  # --------------------
  # GRAYLOG
  # --------------------
  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    depends_on:
      - mongodb
      - opensearch
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9009/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://opensearch:9200
      GRAYLOG_MONGODB_URI: mongodb://mongodb:27017/graylog
    ports:
      - "9009:9000"
      - "12201:12201/udp"
    networks: [net]

  # --------------------
  # SONARQUBE
  # --------------------
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks: [net]

  # --------------------
  # PRODUCER
  # --------------------
  producer:
    build:
      context: ./producer-service
      dockerfile: Dockerfile
    container_name: producer
    depends_on: [kafka1, kafka2, kafka3]
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
    networks: [net]

  # --------------------
  # CONSUMER A
  # --------------------
  consumer-a:
    build:
      context: ./consumer-a
      dockerfile: Dockerfile
    container_name: consumer-a
    depends_on: [kafka1, kafka2, kafka3]
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
    networks: [net]

  # --------------------
  # CONSUMER B
  # --------------------
  consumer-b:
    build:
      context: ./consumer-b
      dockerfile: Dockerfile
    container_name: consumer-b
    depends_on: [kafka1, kafka2, kafka3]
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
    networks: [net]

networks:
  net:
    driver: bridge
