name: Create GitHub Release (Módulo 4 - Kafka Cluster)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: read

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # --------------------------
      # CHECKOUT
      # --------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------
      # JAVA SETUP
      # --------------------------
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # --------------------------
      # BUILD PRODUCER
      # --------------------------
      - name: Build Producer Service
        working-directory: producer-service
        run: |
          chmod +x mvnw
          ./mvnw -B clean package -DskipTests=true

      # --------------------------
      # BUILD CONSUMER A
      # --------------------------
      - name: Build Consumer A
        working-directory: consumer-a
        run: |
          chmod +x mvnw
          ./mvnw -B clean package -DskipTests=true

      # --------------------------
      # BUILD CONSUMER B
      # --------------------------
      - name: Build Consumer B
        working-directory: consumer-b
        run: |
          chmod +x mvnw
          ./mvnw -B clean package -DskipTests=true

      # --------------------------
      # CHANGELOG AUTOMÁTICO
      # --------------------------
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog-config.json"
          toTag: ${{ github.ref_name }}
          outputFile: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --------------------------
      # PUBLICAR RELEASE
      # --------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            producer-service/target/producer-service-*.jar
            consumer-a/target/consumer-a-*.jar
            consumer-b/target/consumer-b-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
